# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d972b34bc7611224c5bd873c94c2b61e181fe9c7c7d5559b9a5dabe8f97324f558b9f511e96d192521a8afc4e3d046cc8d7590cd903758d4316101abcc15414f

test:
  secret_key_base: 1e86ffc53032dd8273cfce456c8fa66ac41f3bae8694a24cd7aa9096542c1b8d1a419fa0aa9d851ed6ce2d31dbadc4cf568f4cde36a009a36f49f444b35fe80c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
